# Generated by Django 3.2.4 on 2021-07-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_shippingaddress_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
